#! /usr/bin/env python

import socket
import sys

def main(args):

    hostname = args[1]
    port = args[2]

    sockSocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    sockSocket.connect((hostname, int(port)))

    sockSocket.send("GET / HTTP/1.0\r\n\r\n")

    while 1:
        buf = sockSocket.recv(1000)
	if not buf:
	   break
	print buf
        
    sockSocket.close()
    
if __name__ == '__main__':
   main(sys.argv)
